In [1]:
import pandas as pd
import os

In [10]:
data_2012 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2012_iuu_insights_v1_pipe4.csv')
data_2013 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2013_iuu_insights_v1_pipe4.csv')
data_2014 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2014_iuu_insights_v1_pipe4.csv')
data_2015 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2015_iuu_insights_v1_pipe4.csv')
data_2016 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2016_iuu_insights_v1_pipe4.csv')
data_2017 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2017_iuu_insights_v1_pipe4.csv')
data_2018 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2018_iuu_insights_v1_pipe4.csv')
data_2019 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2019_iuu_insights_v1_pipe4.csv')
data_2020 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2020_iuu_insights_v1_pipe4.csv')
data_2021 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2021_iuu_insights_v1_pipe4.csv')
data_2022 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2022_iuu_insights_v1_pipe4.csv')
data_2023 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2023_iuu_insights_v1_pipe4.csv')
data_2024 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2024_iuu_insights_v1_pipe4.csv')
data_2025 = pd.read_csv(r'E:\documents\DataScience\practicum\IUU_Regions\regions_2025_iuu_insights_v1_pipe4.csv')

In [3]:
data_2012 = data_2012[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2012['layer'].notnull()]
data_2013 = data_2013[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2013['layer'].notnull()]
data_2014 = data_2014[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2014['layer'].notnull()]
data_2015 = data_2015[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2015['layer'].notnull()]
data_2016 = data_2016[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2016['layer'].notnull()]
data_2017 = data_2017[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2017['layer'].notnull()]
data_2018 = data_2018[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2018['layer'].notnull()]
data_2019 = data_2019[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2019['layer'].notnull()]
data_2020 = data_2020[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2020['layer'].notnull()]
data_2021 = data_2021[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2021['layer'].notnull()]
data_2022 = data_2022[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2022['layer'].notnull()]
data_2023 = data_2023[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2023['layer'].notnull()]
data_2024 = data_2024[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2024['layer'].notnull()]
data_2025 = data_2025[['mmsi','year','hours','active_hours','previously_iuu_listed','iuu_listed','layer']][data_2025['layer'].notnull()]

In [4]:
df_2012 = data_2012.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2013 = data_2013.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2014 = data_2014.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2015 = data_2015.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2016 = data_2016.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2017 = data_2017.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2018 = data_2018.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2019 = data_2019.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2020 = data_2020.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2021 = data_2021.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2022 = data_2022.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2023 = data_2023.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2024 = data_2024.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()
df_2025 = data_2025.groupby('layer').agg({'hours':'sum','active_hours':'sum','mmsi':'count','year':'first'}).reset_index()

In [5]:
df_2025

            layer         hours  active_hours   mmsi  year
0          Arctic  6.237177e+07  2.094988e+07  12809  2025
1  Horn of Africa  1.020040e+05  5.959207e+04     35  2025
2         Oceania  5.854110e+06  4.696760e+06   1154  2025
3   South America  1.382717e+06  9.833028e+05    360  2025

In [11]:
merge_df = pd.concat([df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023, df_2024, df_2025], axis=0)
merge_df['year'] = merge_df['year']
merge_df.rename(columns={'mmsi':'mmsi_count'}, inplace=True)
merge_df

            layer         hours  active_hours  mmsi_count  year
0          Arctic  1.832515e+07  1.004043e+07        5478  2012
1  Horn of Africa  9.293813e+04  7.214843e+04          17  2012
2         Oceania  9.934829e+05  8.568749e+05         204  2012
3   South America  3.952969e+05  3.176621e+05          61  2012
0          Arctic  3.377111e+07  1.666105e+07        8195  2013
1  Horn of Africa  1.027656e+05  6.991933e+04          17  2013
2         Oceania  1.859559e+06  1.591097e+06         330  2013
3   South America  3.834501e+05  2.977623e+05          58  2013
0          Arctic  3.807005e+07  1.821102e+07        9010  2014
1  Horn of Africa  1.298288e+05  8.639608e+04          19  2014
2         Oceania  2.203733e+06  1.862275e+06         395  2014
3   South America  5.366667e+05  4.447154e+05          85  2014
0          Arctic  4.172127e+07  1.958496e+07       10020  2015
1  Horn of Africa  5.075559e+04  2.995275e+04          17  2015
2         Oceania  3.453783e+06  3.032380e+06         683  2015
3   South America  6.192273e+05  5.044713e+05         109  2015
0          Arctic  4.655781e+07  2.097620e+07       10630  2016
1  Horn of Africa  4.404279e+04  1.942203e+04          13  2016
2         Oceania  4.986095e+06  4.347976e+06         820  2016
3   South America  4.371178e+05  3.519978e+05         105  2016
0          Arctic  5.224730e+07  2.116866e+07       11378  2017
1  Horn of Africa  8.417247e+04  5.798191e+04          29  2017
2         Oceania  5.392241e+06  4.620729e+06         925  2017
3   South America  1.027823e+06  8.817292e+05         239  2017
0          Arctic  5.490029e+07  2.228417e+07       11920  2018
1  Horn of Africa  9.859697e+04  5.928856e+04          26  2018
2         Oceania  5.896750e+06  4.954127e+06         999  2018
3   South America  1.022251e+06  8.386269e+05         252  2018
0          Arctic  5.847349e+07  2.253501e+07       12469  2019
1  Horn of Africa  1.089738e+05  8.994400e+04          27  2019
2         Oceania  6.582953e+06  5.535860e+06        1115  2019
3   South America  8.326137e+05  6.283075e+05         231  2019
0          Arctic  5.975454e+07  2.272651e+07       12812  2020
1  Horn of Africa  8.443697e+04  6.397802e+04          24  2020
2         Oceania  6.805664e+06  5.665211e+06        1324  2020
3   South America  1.555193e+06  1.314394e+06         349  2020
0          Arctic  6.318616e+07  2.373821e+07       13097  2021
1  Horn of Africa  7.727481e+04  4.932579e+04          25  2021
2         Oceania  5.979136e+06  4.674512e+06        1284  2021
3   South America  1.938482e+06  1.607805e+06         388  2021
0          Arctic  6.543061e+07  2.319870e+07       13157  2022
1  Horn of Africa  6.777238e+04  4.123226e+04          25  2022
2         Oceania  6.348276e+06  4.993166e+06        1367  2022
3   South America  1.299948e+06  9.623989e+05         333  2022
0          Arctic  6.321047e+07  2.182543e+07       13132  2023
1  Horn of Africa  1.050651e+05  7.085138e+04          26  2023
2         Oceania  6.830387e+06  5.390027e+06        1382  2023
3   South America  1.399485e+06  1.046467e+06         372  2023
0          Arctic  6.314979e+07  2.120555e+07       12835  2024
1  Horn of Africa  8.574484e+04  4.481873e+04          29  2024
2         Oceania  6.044811e+06  4.733928e+06        1289  2024
3   South America  1.269824e+06  8.834013e+05         340  2024
0          Arctic  6.237177e+07  2.094988e+07       12809  2025
1  Horn of Africa  1.020040e+05  5.959207e+04          35  2025
2         Oceania  5.854110e+06  4.696760e+06        1154  2025
3   South America  1.382717e+06  9.833028e+05         360  2025

In [12]:
output_df = pd.read_excel(r'E:\documents\DataScience\practicum\output.xlsx')
output_df

,source_file,event_id,date,year,country,region,Location,latitude,longitude,loc_accuracy,...,IncomeClass_WGI,VAGov_WGI,PVGov_WGI,GEGov_WGI,RGGov_WGI,RLGov_WGI,CCGov_WGI,ClimDisaster_IMF,PplAffect_IMF,TempChange_IMF
0,HOA_FDE_All_Final,e3154,1990-07-18,1990,Somalia,Horn of Africa,Maydh Island,11.221100,47.240300,Town,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.460
1,HOA_FDE_All_Final,e2000,1990-09-29,1990,Kenya,Horn of Africa,Kenyan Lake Victoria Waters,-0.262687,34.193359,Region,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.051
2,HOA_FDE_All_Final,e4086,1991-04-20,1991,Yemen,Horn of Africa,Yemeni waters,16.219717,41.239422,Country,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,30000.0,NaN
3,HOA_FDE_All_Final,e2003,1991-06-01,1991,Kenya,Horn of Africa,Kenya,-0.300862,34.189127,Country,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2700000.0,0.346
4,HOA_FDE_All_Final,e5006,1991-06-01,1991,Yemen,Horn of Africa,yemeni coast,15.759440,41.552469,Country,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,30000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,Oceania_No_AUS_NZL_Final,52223449994,2023-10-31,2023,Samoa,Oceania,Fagaalu Marine Protected Area.,-14.291000,-170.678000,Town,...,Upper middle income,75.617571,87.135763,59.498392,52.185701,75.088207,64.429976,NaN,NaN,0.915
1052,Oceania_No_AUS_NZL_Final,53225464993,2024-03-01,2019,Papua New Guinea,Oceania,"New Ireland Province, Papua New Guinea, specif...",-3.792000,152.622000,Region,...,Lower middle income,55.544024,52.242829,37.209910,46.850980,44.674778,27.873945,2.0,350.0,0.575
1053,Oceania_No_AUS_NZL_Final,54214315906,2024-07-04,2024,French Polynesia,Oceania,"Tautira municipality, French Polynesia.",-17.795000,-149.123000,District,...,High income,72.191156,83.494244,NaN,NaN,74.471348,43.633725,NaN,NaN,0.895
1054,Oceania_No_AUS_NZL_Final,54501479045,2024-08-06,2024,American Samoa,Oceania,"Vaitogi, American Samoa, specifically along th...",-14.357000,-170.738000,Town,...,High income,73.136662,87.298125,66.261470,61.041225,75.665539,71.663617,NaN,NaN,1.588
1055,Oceania_No_AUS_NZL_Final,55022943292,2024-10-11,2024,Samoa,Oceania,"Off the coast of Upolu, Samoa.",-14.084000,-172.243000,Region,...,Upper middle income,72.389498,87.049141,59.788709,53.258241,75.086980,61.783305,NaN,NaN,1.493

In [13]:
final_df = pd.merge(merge_df, output_df, how='right', left_on=['layer','year'], right_on=['region','year'])
final_df.drop(['layer'], axis=1, inplace=True)
final_df

,hours,active_hours,mmsi_count,year,source_file,event_id,date,country,region,Location,...,IncomeClass_WGI,VAGov_WGI,PVGov_WGI,GEGov_WGI,RGGov_WGI,RLGov_WGI,CCGov_WGI,ClimDisaster_IMF,PplAffect_IMF,TempChange_IMF
0,NaN,NaN,NaN,1990,HOA_FDE_All_Final,e3154,1990-07-18,Somalia,Horn of Africa,Maydh Island,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.460
1,NaN,NaN,NaN,1990,HOA_FDE_All_Final,e2000,1990-09-29,Kenya,Horn of Africa,Kenyan Lake Victoria Waters,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.051
2,NaN,NaN,NaN,1991,HOA_FDE_All_Final,e4086,1991-04-20,Yemen,Horn of Africa,Yemeni waters,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,30000.0,NaN
3,NaN,NaN,NaN,1991,HOA_FDE_All_Final,e2003,1991-06-01,Kenya,Horn of Africa,Kenya,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2700000.0,0.346
4,NaN,NaN,NaN,1991,HOA_FDE_All_Final,e5006,1991-06-01,Yemen,Horn of Africa,yemeni coast,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,30000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,6.830387e+06,5.390027e+06,1382.0,2023,Oceania_No_AUS_NZL_Final,52223449994,2023-10-31,Samoa,Oceania,Fagaalu Marine Protected Area.,...,Upper middle income,75.617571,87.135763,59.498392,52.185701,75.088207,64.429976,NaN,NaN,0.915
1052,6.582953e+06,5.535860e+06,1115.0,2019,Oceania_No_AUS_NZL_Final,53225464993,2024-03-01,Papua New Guinea,Oceania,"New Ireland Province, Papua New Guinea, specif...",...,Lower middle income,55.544024,52.242829,37.209910,46.850980,44.674778,27.873945,2.0,350.0,0.575
1053,6.044811e+06,4.733928e+06,1289.0,2024,Oceania_No_AUS_NZL_Final,54214315906,2024-07-04,French Polynesia,Oceania,"Tautira municipality, French Polynesia.",...,High income,72.191156,83.494244,NaN,NaN,74.471348,43.633725,NaN,NaN,0.895
1054,6.044811e+06,4.733928e+06,1289.0,2024,Oceania_No_AUS_NZL_Final,54501479045,2024-08-06,American Samoa,Oceania,"Vaitogi, American Samoa, specifically along th...",...,High income,73.136662,87.298125,66.261470,61.041225,75.665539,71.663617,NaN,NaN,1.588
1055,6.044811e+06,4.733928e+06,1289.0,2024,Oceania_No_AUS_NZL_Final,55022943292,2024-10-11,Samoa,Oceania,"Off the coast of Upolu, Samoa.",...,Upper middle income,72.389498,87.049141,59.788709,53.258241,75.086980,61.783305,NaN,NaN,1.493

In [14]:
final_df.to_csv(r'E:\documents\DataScience\practicum\IUU_outputWith2012.csv', index=False)

In [16]:
final_output = pd.read_csv(r'E:\documents\DataScience\practicum\final_output.csv')
final_output.drop(['hours_previous_year','active_hours_previous_year','mmsi_count_previous_year'], axis=1, inplace=True)
final_output = pd.merge(merge_df, final_output, how='right', left_on=['layer','year'], right_on=['region','year'])
final_output.drop(['layer'], axis=1, inplace=True)
final_output.to_csv(r'E:\documents\DataScience\practicum\final_output_with_2012.csv', index=False)